### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by CaiIsProgrammer** [Paciolan/remote-component-starter#11]
It doesn't really tell you how to deploy the component to be used once created. How can i go about to do this

**Comment by joelnet** [comment]
You would deploy it the same way you regularly deploy things. When you build, it'll create a `dist` folder. You will find the JavaScript that need to be published in there. It just need to sit at a location accessible via the web. So if you can access it via `http` or `https` you are good. I like to publish to an S3 bucket, but it's up to you where you would like to publish to.

**Comment by CaiIsProgrammer** [comment]
well do i just get the main.js file? or which file do i call for?

**Comment by joelnet** [comment]
This is a good question. I think the documentation needs to be improved in this area. You need to publish the `main.js` file. That is what you will point to when importing a remote component. 👍
